services:
  db:
    image: postgres:17-alpine
    container_name: techstore-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: techstore
      POSTGRES_USER: techstore
      POSTGRES_PASSWORD: techstore
    ports:
      - "5432:5432"
    volumes:
      - techstore_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techstore -d techstore"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  techstore_pgdata:
