/**
 * Painel administrativo do projeto.
 * Exibe métricas da API e administra produtos reais via React Query.
 */

import { useState, type FormEvent } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, categoryService, productService } from '../services/api'
import { money } from '../utils/format'
import type { Product } from '../types'

// Modelo utilizado para inicializar o formulário de um novo produto.
const emptyProduct: Product = { id: '', name: '', slug: '', sku: '', description: '', price: 0, stock: 0, category: '', categoryId: '', emoji: '📦', featured: false }

// Página disponível somente para role ADMIN por meio de AdminRoute.
export default function AdminPage() {
  const qc = useQueryClient()
  const { data: products = [], isLoading, error } = useQuery({ queryKey: ['products'], queryFn: productService.list })
  const { data: categories = [] } = useQuery({ queryKey: ['categories'], queryFn: categoryService.list })
  const { data: dashboard } = useQuery({ queryKey: ['admin-dashboard'], queryFn: () => api<{ customers: number; activeProducts: number; orders: number; pendingOrders: number; lowStockProducts: number; revenue: number }>('/admin/dashboard') })
  const [editing, setEditing] = useState<Product | null>(null)
  const [form, setForm] = useState<Product>(emptyProduct)
  const saveMutation = useMutation({ mutationFn: productService.save, onSuccess: () => { qc.invalidateQueries({ queryKey: ['products'] }); qc.invalidateQueries({ queryKey: ['admin-dashboard'] }); setEditing(null); setForm(emptyProduct) } })
  const removeMutation = useMutation({ mutationFn: productService.remove, onSuccess: () => { qc.invalidateQueries({ queryKey: ['products'] }); qc.invalidateQueries({ queryKey: ['admin-dashboard'] }) } })
  const startNew = () => { const category = categories[0]; setEditing(emptyProduct); setForm({ ...emptyProduct, category: category?.name || '', categoryId: category?.id || '' }) }
  const edit = (product: Product) => { setEditing(product); setForm({ ...product }) }
  const submit = (event: FormEvent) => { event.preventDefault(); saveMutation.mutate(form) }
  const inventory = products.reduce((sum, product) => sum + product.stock * product.price, 0)
  const isExisting = Boolean(editing?.id && products.some(product => String(product.id) === String(editing.id)))
  return <section className="section admin-section"><div className="container"><div className="admin-header"><div><span className="eyebrow">Painel administrativo</span><h1>Visão geral da loja</h1></div><button className="btn btn-primary" onClick={startNew}>+ Novo produto</button></div><div className="metrics"><div className="metric"><span>📦</span><div><small>Produtos ativos</small><strong>{dashboard?.activeProducts ?? products.length}</strong></div></div><div className="metric"><span>⚠️</span><div><small>Estoque baixo</small><strong>{dashboard?.lowStockProducts ?? products.filter(p=>p.stock<=5).length}</strong></div></div><div className="metric"><span>💰</span><div><small>Valor em estoque</small><strong>{money(inventory)}</strong></div></div><div className="metric"><span>🧾</span><div><small>Pedidos</small><strong>{dashboard?.orders ?? '—'}</strong></div></div></div>
  {error && <div className="form-error">{(error as Error).message}</div>}{saveMutation.error && <div className="form-error">{(saveMutation.error as Error).message}</div>}{removeMutation.error && <div className="form-error">{(removeMutation.error as Error).message}</div>}
  <div className="panel admin-table-wrap"><div className="panel-title"><h3>Produtos</h3><span>Dados sincronizados com a API</span></div>{isLoading ? <div className="loader">Carregando produtos...</div> : <div className="table-scroll"><table className="admin-table"><thead><tr><th>Produto</th><th>SKU</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Ações</th></tr></thead><tbody>{products.map(product=><tr key={product.id}><td><div className="table-product"><span>{product.emoji}</span><div><strong>{product.name}</strong><small>{product.featured?'Destaque':' '}</small></div></div></td><td>{product.sku}</td><td>{product.category}</td><td>{money(product.price)}</td><td><span className={product.stock<=5?'stock-pill low':'stock-pill'}>{product.stock}</span></td><td><button className="table-btn" onClick={()=>edit(product)}>Editar</button><button className="table-btn danger" onClick={()=>{if(confirm('Desativar este produto?'))removeMutation.mutate(product.id)}}>Desativar</button></td></tr>)}</tbody></table></div>}</div>
  {editing&&<div className="modal-backdrop" onMouseDown={()=>setEditing(null)}><div className="modal" onMouseDown={event=>event.stopPropagation()}><div className="modal-head"><h2>{isExisting?'Editar produto':'Novo produto'}</h2><button onClick={()=>setEditing(null)}>×</button></div><form onSubmit={submit} className="form"><div className="form-grid"><label className="wide">Nome<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})} required minLength={2} /></label><label>SKU<input value={form.sku||''} onChange={event=>setForm({...form,sku:event.target.value})} placeholder="TS-PRODUTO-001" required /></label><label>Slug<input value={form.slug||''} onChange={event=>setForm({...form,slug:event.target.value})} placeholder="nome-do-produto" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" /></label><label className="wide">Categoria<select value={form.categoryId||''} onChange={event=>{const category=categories.find(item=>item.id===event.target.value);setForm({...form,categoryId:event.target.value,category:category?.name||''})}} required><option value="" disabled>Selecione</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Preço<input type="number" min="0" step="0.01" value={form.price} onChange={event=>setForm({...form,price:Number(event.target.value)})} required /></label><label>Estoque<input type="number" min="0" step="1" value={form.stock} onChange={event=>setForm({...form,stock:Number(event.target.value)})} required /></label><label className="wide">URL da imagem<input type="url" value={form.imageUrl||''} onChange={event=>setForm({...form,imageUrl:event.target.value})} placeholder="https://..." /></label><label className="wide">Descrição<textarea rows={4} minLength={10} value={form.description} onChange={event=>setForm({...form,description:event.target.value})} required /></label><label style={{display:'flex',alignItems:'center',gap:8}}><input type="checkbox" checked={Boolean(form.featured)} onChange={event=>setForm({...form,featured:event.target.checked})} /> Produto em destaque</label></div><div className="modal-actions"><button type="button" className="btn btn-ghost" onClick={()=>setEditing(null)}>Cancelar</button><button className="btn btn-primary" disabled={saveMutation.isPending || categories.length===0}>{saveMutation.isPending?'Salvando...':'Salvar produto'}</button></div></form></div></div>}
  </div></section>
}
